### ISSUE TITLE
DuckieTV 1.1.6 publishing check list

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#1086]
# TODO check list (add or subtract as required):

## pre-release check list
- [x] prep/check the version to 1.1.6 as required (VERSION, MANIFEST, PACKAGE, etc).
- [x] hide any w.i.p. pages or features using some html tricks
  - [x] multi-SE ADS
- [x] fix any outstanding urgent bugs
  - [x] sidepanel close buttons not clickable #1085
- [x] prep/check the changelog in readme
- [x] prep/check the migrationService
- [x] prep/check the upgradeNotificationService
- [x] check/update all the translations tables for missing/outdated keys

### Schizoduckie's check list:
- [ ] update pre-release title at https://github.com/SchizoDuckie/DuckieTV/releases/tag/1.1.6    
- [ ] and remove the pre-release tag check box    
- [ ] publish 1.1.6 for all platforms    
- [ ] check/update the changelog on google chrome store new-tab
- [ ] check/update the changelog on google chrome store action-mode
- [ ] make announcement on Reddit https://www.reddit.com/r/duckietv/    
- [ ] make announcement on Facebook https://www.facebook.com/DuckieTV/    

### Garfield69's post publishing check list:
- [ ] update changelog in https://github.com/SchizoDuckie/DuckieTV/blob/angular/README.md    
- [ ] update changelog in https://github.com/SchizoDuckie/DuckieTV/blob/gh-pages/_posts/2015-01-12-changelog.md    
- [ ] bump version to 1.1.7    
    - [ ] https://github.com/SchizoDuckie/DuckieTV/blob/angular/VERSION    
    - [ ] https://github.com/SchizoDuckie/DuckieTV/blob/angular/package.json    
    - [ ] https://github.com/SchizoDuckie/DuckieTV/blob/angular/manifest.json    
    - [ ] https://github.com/SchizoDuckie/DuckieTV/blob/angular/manifest-app.json     
- [ ] have a beer

**Comment by garfield69** [comment]
good to go.

**Comment by lgmorand** [comment]
can we expect the 1.6 for Xmas ? :) it would be great, especially with all that fixes only present in the nightly !

**Comment by AlienProber** [comment]
Xmas of what year? **3**020?

**Comment by lgmorand** [comment]
@SecretAgentAgentX ohhh, you auto-censured yourself ? chicken ! :D

**Comment by AlienProber** [comment]
> @SecretAgentAgentX ohhh, you auto-censured yourself ? chicken ! :D

FUCKIN WORTHLESS ASSHOLE.

**Comment by garfield69** [comment]
Closing.  Mostly due to Google.

Nightly releases are the only reliable current method to provide Standalone Dtv packages for now.

The Nightly Chrome Extensions are available only via the Extensions page Development mode manual install, as the Google Chrome Web store rejects Dtv updates due to Dec-2019 security rules, which are impractical for  Dtv to comply with.

**Comment by lgmorand** [comment]
pretty clear the explanation, thanks garfield, I'll go for nightlies then. but then, is this not simplier (I don't have your vision on the source code/project) to publish a last supported extension (1.15) and have a separate living version for the standalone which continues to live ?

I'm only using the standalone and I don't know how many people are using the extension or a nightly of the extension
