### ISSUE TITLE
Todo's for the 0.75 release?

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#274]
I've just put the last addition of the 'hover menu' on hold for a future release so we can get 0.75 out the door.

Todo list, I guess: 
- [x] Add a v0.75 upgrade screen
- [x] Try out the packaging system on all platforms
- [x] One last round of overall bug checks?
- [x] Anything else?

[edit: wtf these checkboxes are awesome and clickable :astonished: ]
