### ISSUE TITLE
DuckieTV v1.00 release checklist

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#413]
- [x] ~~any open tickets to be completed before v1 is released, add here~~
- [x] #416 
- [x] bump versions to 1.00
- [x] any additional updates to manifest*.json, package.json
- [x] implement OpenSubtitles useragent (DuckieTV v1.00)
- [x] update readme.md changelog
- [x] create a simple github upgrade notification check for standalone releases
- [x] perform a 1-time-pass during the v1.00 upgrade, CRUD.EntityManager.getAdapter().db.execute("update Episodes set downloaded = 1 where watched == 1")
- [x] update UpgradeNotificationService.js
- [x] update gulpfile.js
- [x] update gh-pages _post/2015-01-12-changelog.md
- [x] ~~any tests to be completed, add here~~
- [x] test upgrade/migration services on an existing 0.94 DB (Chrome Ext)
- [x] test upgrade/migration services on an existing 0.55 DB (Opera Ext)
- [x] test upgrade/migration services on a fresh install (Chrome Ext)
- [x] test upgrade/migration services on an existing 0.94 DB (Standalone)
- [x] test upgrade/migration services on a fresh install (Standalone)
- [x] build distribution standalones
- [x] tag release
- [x] ~~anything else~~
- [x] migrate newtab and action mode to chrome store
- [x] have a beer or other celebratory beverage \o/

-  ~~migrate to opera this time ;-) ?~~

**Comment by SchizoDuckie** [comment]
59716073019d39a246e0220239cee6a202b115eb

**Comment by SchizoDuckie** [comment]
Allright guys, so help me out here with a changelog.

- Completely revamped user interface 
- Added support for Tixati, Transmission and qBittorrent torrent clients
- Added Stripe torrent search
- Initial version of Subtitle search available from episodes panel
- Removed Chromecast integration. (Use getvideostream.com and the app!) 
- too many small changes to list 
- feel free to add important things

**Comment by garfield69** [comment]
- Added Strike and RARBG torrent search
- Made Standalone use Frame-less windows and added 1:1 chrome-like zooming
- Database performance improvement (including less frequent ratings updates)
- Added episode-downloaded highlighting to the calendar and related
management controls
- Added play-on-Netflix button for episodes released by them

  _____

**Comment by garfield69** [comment]
completed my contributions to the list.

**Comment by SchizoDuckie** [comment]
Sweet. thanks! Feel free to update the readme. i'm hitting the sack.

**Comment by SchizoDuckie** [comment]
@garfield69 

 >  (should we include a database pass setting all episodes that are watched to downloaded ?)

what do you mean by this?

**Comment by garfield69** [comment]
After the upgrade there will be episodes in the database that will have a status of watched but not-downloaded. Which would not make sense.

So I thought the upgrade process should probably include a one time pass through the database, setting all episodes that have been previously marked as watched as also downloaded.

**Comment by SchizoDuckie** [comment]
Yeah good idea :)

    update Episodes set downloaded = 1 where watched = 1

should do.

**Comment by SchizoDuckie** [comment]
- [x] [create introductional youtube video](https://www.youtube.com/watch?v=cipuVrQU0UU)

**Comment by garfield69** [comment]
Nice presentation. Shame the music was not on a loop, ends part way through.
This completed #361 then?
  ----- Original Message -----

**Comment by SchizoDuckie** [comment]
Hmm ah! i'll try to loop the soundtrack somewhere tonight. it didn't do
that in the editor!

**Comment by SchizoDuckie** [comment]
My gf's machine has some dupe episode (again, or still, idunno)

Was able to figure the pattern out using some sql:

    select group_concat(ID_Episode) as affected from episodes  group by  ID_Serie, seasonnumber, episodenumber having count(seasonnumber||','||episodenumber) > 1;

    delete  from episodes where (TVDB_ID IS null OR  episodename IS null or firstaired_iso IS null or     IMDB_ID IS NULL) and ID_Episode in ( 
	<comma separated affected list>
)  order by ID_Serie, seasonnumber, episodenumber LIMIT 0, 1000;

**Comment by garfield69** [comment]
on standalone, I'm not getting an upgrade notify popup and the local storage key is still set to 0.94.
![image](https://cloud.githubusercontent.com/assets/6933240/7623865/30ab6716-fa34-11e4-925f-5ff1483dfa88.png)

**Comment by SchizoDuckie** [comment]
Yeah i have a problem with the migrationservice / .run block too. it doesnt seem to be executing on a clean install. will test some more, release will be tomorrow, after some sleep

**Comment by garfield69** [comment]
\o/ notifications working now.

**Comment by garfield69** [comment]
\o/ fresh install and 0.94->1.0 chrome ext success. Barring any other surprises, should be ready for distribution tomorrow.

**Comment by SchizoDuckie** [comment]
Excellent news. really glad we caught and fixed this! 

I'll be prepping the release

**Comment by SchizoDuckie** [comment]
Woohoo! 1.0 is live!

Now for a shower and some beers.

I'm not sure if i'm going to do another opera release. It's a lot of work back-and-forthing with them and they require changes constantly. Plus, with the standalone version there's a proper alternative.
