### ISSUE TITLE
Sexy Poster Transition Tracker

### ISSUE THREAD

**Issue by Js41637** [SchizoDuckie/DuckieTV#465]
Issue tracker for Sexy Poster Transitions stuff.

- [x] Switching between miniposter and poster needs to recalculate positions
- [x] Need to center align the posters to page
- [x] Make height from top of page consistent (Miniposters are ok but large posters are too far down)
- [x] Make the calculations obey the paddings on the series-list (.series) and not go over
- [x] If possible, properly center posters to middle ([img](http://puu.sh/ixbMu/ffca4cd9e6.jpg))
- [x] Add horizontal offset option (I think Duckie started to add it but didn't add the code, would fix the need for obeying paddings as we could specify horizontal offset/2 for each side

**Comment by SchizoDuckie** [comment]
Looks mighty fine to me
