### ISSUE TITLE
Allow setting custom download location per serie for torrent clients that support it

### ISSUE THREAD

**Issue by SchizoDuckie** [SchizoDuckie/DuckieTV#508]
As requested on Reddit: 

https://www.reddit.com/r/duckietv/comments/3d5iv4/custom_download_locations/

Requirements:
- [x] Document code and API source in all torrent clients
- [x] Flag torrent clients that support this feature
  - [x] deluge *Supported*
  - [x] Ktorrent **NOT** *Supported*
  - [x] qBittorrent 3.2+
    - API6 Pre 3.3.1 **NOT** *Supported*
    - API7 3.3.1+ *Supported*
  - [x] qBittorrent pre3.2 **NOT** *Supported*
  - [x] rTorrent *Supported*
  - [x] Tixati **NOT** *Supported*
  - [x] Transmission / Vuze *Supported*
  - [x] uTorent API **NOT** *Supported*
  - [x] uTorrent WEBUI **NOT** *Supported*
- [x] ~~Create a customDownloadLocationSupported flag in base torrentclient config that's false~~
- [x] Create an isDownloadPathSupported function in base torrentclient that's false
- [x] ~~Overwrite customDownloadLocationSupported flag for clients that support it~~
- [x] Overwrite isDownloadPathSupported for clients that support it
- [x] Implement setting custom download location for each client API that supports it
  - [x] deluge
  - [x] qBittorrent 3.2+ API7+
  - [x] rTorrent
  - [x] Transmission / Vuze
- [x] Implement new setting per show that allows to set a file path when a torrentclient is selected that has customDownloadLocationSupported (Directory picker possible? otherwise type a path)
- [x] Implement new db field for Serie (+ migration) to store this path
- [x] ~~Check customDownloadLocationSupported supported for torrentclient when launching an episode torrent~~
- [x] Fetch customDownloadLocation when set for serie
- [x] pass ~~both~~ it to torrent client api
- [x] if client is remote then use text input for setting dlPath (not nwdirectory)

**Comment by Fabhawk** [comment]
Hi Guy !

Any update on this one ? it would be a great enhancement
Thanks in advance.

**Comment by garfield69** [comment]
No progress on this one so far.     

 I personally have no use for it, I use FileBot to auto move and rename all my shows to their final destination. I wrote a wiki a while back to help with the basic set up https://github.com/SchizoDuckie/DuckieTV/wiki/Pairing-DuckieTV-with-FileBot-for-a-fully-automated-media-center, although admittedly it is aimed at window users using uTorrent.    
But I accept there are users out there that don't want to use Filebot or have the skills to customise it to make it work for their platform/configuration, so....     

I will take a look at this after I finish with #769, and get the first two items on the check list done, then we can evaluate if the percentage of torrent hosts is high enough to warrant implementing the rest.

**Comment by garfield69** [comment]
**todo**: instead of using an *input type="text"* for the *dlPath* on our angular-formly form, we may be able to use a modified *input type="file"* that allows up to get a directory path. This would provide some validation that the path is good, which the current text field does not give us, unless we write a complex validation script that handles mac,linux and windows paths.    
so   
```
}, {
    "key": "dlPath",
    "className": "col-xs-12",
    "type": "input",
    "hideExpression": "!model.isDownloadPathSupported",
    "templateOptions": {
        "type": "text", 
        "label": ""
    },
    "expressionProperties": {
        "templateOptions.label": "\"SERIESETTINGSCTRLjs/dl-path/lbl\" | translate",
        "templateOptions.placeholder": "\"SERIESETTINGSCTRLjs/dl-path/placeholder\" | translate"
    }
```    
becomes    
```
}, {
    "key": "dlPath",
    "className": "col-xs-12",
    "type": "input",
    "hideExpression": "!model.isDownloadPathSupported",
    "templateOptions": {
        "type": "file", 
        "label": ""
    },
    "expressionProperties": {
        "templateOptions.label": "\"SERIESETTINGSCTRLjs/dl-path/lbl\" | translate",
    }
```    
Only problem is we need to work out how to pass the following attributes to that field's template     
```
nwdirectory directory
```
