### ISSUE TITLE
[Request] Support For Jackett

### ISSUE THREAD

**Issue by zero77** [SchizoDuckie/DuckieTV#899]
Can you please look at adding support for Jackett https://github.com/Jackett/Jackett because, it supports a wide range of torrent search engines and it may decrease your work load.
Thanks

**Comment by garfield69** [comment]
DuckieTV team:      
I have researched the Jackett proxy, and I believe we can make use of this tool with DuckieTV to provide support for private, semi-private and open web sites, for our search engine usage.      
Jackett works on Windows with .NET 4 (as either a installed service, or a run-time program), and on Linux and osX with Mono 4.     
There is not Android support.     

An additional advantage of using Jackett is its ability to handle most cloudflare DDOS and other redirection challenges.     

I have not tested it against private sites, but I don't expect any issues, Jackett is currently used by Sonarr, Radarr, SickRage, CouchPotato and Mylar users.      

On my windows sandbox I have successfully tested replacement DuckieTV SE for ThePirateBay, LimeTorrents, SkyTorrents, RarBG, TorrentZ2, Nyaa.si, Katcr, EzTV.ag and soHunt, using the Jackett's Admin http interface, since this returns plain json results, which makes it fairly straight forward to plug into our GenericSearchEngine.      

I have also coded and tested support for the Jackett torznab API, but this returns XML only.    
I process this with x2js (which we already use for the Ktorrent client), but the results then require further processing overhead to mine the required data we want.      
I don't think we need this API, since we are not making complicated search requests, we just make general search queries without additional parameters. IMO the Jackett Admin interface is more that sufficient for this use.         

@SchizoDuckie  I propose to allow use of Jackett with DuckieTV, with a view to replacing the currently incomplete CustomSearchEngine project, which I don't see anyone making time to advance to completion any time soon.     

So we would continue to provide the existing default Search engines, but allow the user to enable Jackett support, and allow them to define Jackett Search Engine entries, which would work alongside the default Search Engines, or replace them if the user choose to give them the same name.     

# tasks:    
- [x] define a Jackett DB table     
- [x] create settings GUI to:     
    - [x] add a Jackett SE definition     
    - [x] enable/disable it     
    - [x] delete it     
- [x] add support to TorrentSearchEngine so that any Jackett SE that are enabled will replace the default SE with the same names (in the same way the customSearchEngines definitions currently can).     
- [x] add support to GenericSearchEngine to allow Jackett configs to perform search requests, process the results and present them to Search Dialogues and Auto-Download, in the same way as current SE can do.     
- [x] add wiki instructions for using Jackett with DuckieTV     
- [ ] remove customSearchEngine stuff
  - [x] ctrl and settings js    
  - [x] templates, dialogues, forms     
  - [x] DB entity       
  - [x] Table in DB
- [x] translations

**Comment by SchizoDuckie** [comment]
I have no interest myself in jackett, but I see the points you're making.

go ahead, give it a shot if you're up for it.


On 21 May 2017 02:55, "garfield69" <notifications@github.com> wrote:

DuckieTV team:
I have researched the Jackett proxy, and I believe we can make use of this
tool with DuckieTV to provide support for private, semi-private and open
web sites, for our search engine usage.
Jackett works on Windows with .NET 4 (as either a installed service, or a
run-time program), and on Linux and osX with Mono 4.
There is not Android support.

An additional advantage of using Jackett is its ability to handle most
cloudflare DDOS and other redirection challenges.

I have not tested it against private sites, but I don't expect any issues,
Jackett is currently used by Sonarr, Radarr, SickRage, CouchPotato and
Mylar users.

On my windows sandbox I have successfully tested replacement DuckieTV SE
for ThePirateBay, LimeTorrents, SkyTorrents, RarBG, TorrentZ2, Nyaa.si,
Katcr, EzTV.ag and soHunt, using the Jackett's Admin http interface, since
this returns plain json results, which makes it fairly straight forward to
plug into our GenericSearchEngine.

I have also coded and tested support for the Jackett torznab API, but this
returns XML only.
I process this with x2js (which we already use for the Ktorrent client),
but the results then require further processing overhead to mine the
required data we want.
I don't think we need this API, since we are not making complicated search
requests, we just make general search queries without additional
parameters. IMO the Jackett Admin interface is more that sufficient for
this use.

@SchizoDuckie <https://github.com/schizoduckie> I propose to allow use of
Jackett with DuckieTV, with a view to replacing the currently incomplete
CustomSearchEngine project, which I don't see anyone making time to advance
to completion any time soon.

So we would continue to provide the existing default Search engines, but
allow the user to enable Jackett support, and allow them to define Jackett
Search Engine entries, which would work alongside the default Search
Engines, or replace them if the user choose to give them the same name.
tasks:

   - define a Jackett DB table
   - create settings GUI to:
      - add a Jackett SE definition
      - enable/disable it
      - delete it
   - add support to TorrentSearchEngine so that any Jackett SE that are
   enabled will replace the default SE with the same names (in the same way
   the customSearchEngines definitions currently can).
   - add support to GenericSearchEngine to allow Jackett configs to perform
   search requests, process the results and present them to Search Dialogues
   and Auto-Download, in the same way as current SE can do.
   - add wiki instructions for using Jackett with DuckieTV
   - remove customSearchEngine code and templates etc

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/SchizoDuckie/DuckieTV/issues/899#issuecomment-302908018>,
or mute the thread
