### ISSUE TITLE
add .torrent processing to auto-download service

### ISSUE THREAD

**Issue by garfield69** [SchizoDuckie/DuckieTV#916]
Currently the Auto-Download Service does not make use of .torrents.      

Why?      
The original reason was that in order for the ADS to mark an episode as downloaded we need to track the torrent on the host via the torrent client, so that we know when the download is completed.      
In order to do this we need a reliable way to identify which torrent on the host relates to the episode we are trying to keep up to date.      

Why do we need to track the torrent progress?     
If we do not track the torrent on the host, then we run into the situation where the next run of the ADS in 15 minutes time will resubmit the next suitable torrent.   This may not necessarily even be the same .torrent found 15 minutes ago. You could get duplicate downloads, or bombard the user every 15 minutes with torrent host pop-ups asking to merge the new torrent info with the existing one.      
Users doing post-download processing via FileBot or other methods could also run into problems.     

Why not just mark the episode as downloaded automatically at the start?     
If we mark the episode as downloaded at the start when we submit the .torrent to the host, then we are reliant on the user to cross check everything is OK at some point, and manually making adjustments as required, which kind of defeats the point of automating the download process.     
Should the torrent download fail, or cannot find any seeders to get started, or any number of torrent related problems, then the user will have to manually adjust the episode status and reset for another ADS search.      
They will need to manually identify which episode the problematic torrent download is associated with.     
While managing one or two torrents is negligible, some users have multiple episodes downloading per day, with multiple torrents active while they do seeding, and keeping track of all that activity manually will become tiresome in no time.     
Others have DuckieTV running 24/7 and rely on the automation keeping track of everything smoothly.     
Users that have just begun using DuckieTV, and set a 21 day ADS search would be kept quite busy.     

So whats the problem with .torrent files identification?     
Unfortunately, the .torrent file name provided by the Search Provider is not reliable, as once the .torrent file is loaded to the torrent host, the internal file name within the .torrent file is used, which is sometimes (often?) not the same.      
We currently do a filename versus episodeName matching attempt for .torrents submitted manually via the torrent search dialogue, but this is a hit or miss affair, and not 100% reliable.      
The HashInfo is always unique however, but we currently do not have a method to extract that from the .torrent file so we cannot use it for tracking, like we currently can do for magnets.     

So whats the point of this ticket?     
So the goal here is to research available methods to reliably identify a .torrent file on the connected torrent host so we can automatically mark the associated episode as downloaded.
We want to avoid ADS from resubmitting torrents, and avoid  relying on /taxing the user to manually keep the episodes status up to date.      
The preferred method is to somehow get the InfoHash from the .torrent file.

**Comment by kevincaradant** [comment]
Hi

I didn't have the time to search solution yet. But it's just a library I found on github about the reading of torrent:
[READ TORRENT](https://github.com/mafintosh/read-torrent)

Maybe that can be useful for you ?

**Comment by garfield69** [comment]
>I didn't have the time to search solution yet. But it's just a library I found on github about the reading of torrent: READ TORRENT Maybe that can be useful for you ?     

Thanks. NPM java is not suitable for DuckieTV, but it may be possible to convert the critical bits of it into AngularJS. At the very least it gives us hope that a solution is possible.

**Comment by kevincaradant** [comment]
Java ? The library is in js no ? Maybe I miss something :).Anyway,  Im happy if that can help you in the case where you don t find better

**Comment by garfield69** [comment]
Typo. I meant JavaScript ;-)

 

  _____

**Comment by garfield69** [comment]
# tasks list:

### coding:

- [x] port NPM parse-torrent
- [x] add .torrent handling to AutoDownloadService 
  - [x] rewrite magnet/torrent search-page and details-page processing
  - [x] call parse-torrent to add infoHash parm to launchTorrentByUpload and launchTorrentByURL calls
- [x] change TD and TD2 dialogues 
  - [x] invoke launchTorrentByUpload instead of openTorrentLink
  - [x] call parse-torrent to add infoHash parm to launchTorrentByUpload and launchTorrentByURL calls
- [x] add infoHash parm pass-through to baseTorrentClient calls of addTorrentByUpload and addTorrentByURL
- [x] change torrent clients by replacing match-by-torrentName with match-by-infoHash in addTorrentByUpload and addTorrentByURL routines
  - [x] deluge
  - [x] Ktorrent
  - [x] qBitTorrent pre 3.2
  - [x] qBitTorrent 3.2+
  - [x] rTorrent
  - [x] Tixati
  - [x] Transmission/Vuze
  - [x] uTorrent API
  - [x] uTorrent WEBUI
- [x] amend torrentSearchEngine to provide InfoHash parm for client calls
- [x] replace ADmonitor magnet status translations with torrent (has magnet -> has torrent, magnet launched -> torrent launched)

### testing:

- [x] test AD with .torrent only SE (such as demonoid) on windows7 (by default)
  - [x] deluge
  - [x] Ktorrent (ubuntu 17.04)
  - [x] qBitTorrent pre 3.2
  - [x] qBitTorrent 3.2+
  - [x] rTorrent (ubuntu 17.04)
  - [x] Tixati
  - [x] Transmission
  - [x] Vuze
  - [x] uTorrent API
  - [x] uTorrent WEBUI
- [x] test TD with .torrent only SE (such as demonoid) on windows
- [x] test TD2 with .torrent only SE (such as demonoid) on windows
- [x] check magnet processing still works ;-)

### docs:
- [x] amend wiki ADS FAQ
  - [x] drop AD-disabled-NM section
  - [x] drop any only-magnets-are-supported paragraphs
- [x] search and remove any other wiki pages paragraphs that mention AD supporting only magnets

**Comment by kevincaradant** [comment]
So you are already ready to test ? You re are fast to improve DuckieTV :) 

Some bad news, T411 exists since many and many years. It was the best website for that but since one week, T411 is down / destroyed  because of the police... So I can't try with this. Im so sad because I was configured everything in auto to try your feature. But I will try to find a moment to try with other links in torrent ')

**Comment by garfield69** [comment]
Yeah, saw the article about t411 on torrentfreak last week. Bad luck.          
I did preliminary testing against demonoid when I was developing the code.     
I'll conduct a full battery of tests after Wimbledon is over. Right now I'm about to begin immersing full time into watching tennis :-)

**Comment by kevincaradant** [comment]
Haha Alright. If you need some endusers,  write here. So, Enjoy with your tennis :p

**Comment by zero77** [comment]
Can you add a default torrent download path, so you don’t have to select one for each show individually.

**Comment by garfield69** [comment]
>Can you add a default torrent download path, so you don’t have to select one for each show individually.       

@zero77  you configure the default download path at your torrent Host :-)

**Comment by garfield69** [comment]
\o/

**Comment by zero77** [comment]
> you configure the default download path at your torrent Host :-)
Thanks, i will do it that way then.
